spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.format-sql=true
spring.sql.init.mode=always
spring.kafka.bootstrap-servers=kafka:9092
eureka.client.service-url.defaultZone=http://eureka:8761/eureka